name: Docker Image CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SHA: $(git rev-parse --short HEAD)
    steps:

    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Declare variables
      id: vars
      shell: bash
      run: GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c1-8)

    - name: docker build
      run: docker build . -t shtrull/example-docker:latest

    - name: docker tag by commit hash
      run: docker tag shtrull/example-docker:latest "shtrull/example-docker:${{ SHA }}"

    - name: docker push (multiple lines)
      run: |
        docker push "shtrull/example-docker:latest"
        docker push "shtrull/example-docker:${{ SHA }}"
